import { ArrowRight, BarChart3, CalendarCheck, MapPin, ShieldCheck, Sparkles, Star } from "lucide-react";

const diagnosticAreas = ["Local visibility", "Google trust", "Pricing confidence", "Patient recall", "Brand authority"];

const painCards = [
  { title: "Empty Slots", copy: "Your calendar has space, but local patients do not know why they should choose you." },
  { title: "Pricing Guilt", copy: "You keep fees low to avoid resistance, then pay for it through burnout and unstable income." },
  { title: "Invisible Trust", copy: "Patients search before they book. If your digital presence is weak, your expertise stays hidden." }
];

const method = [
  { label: "Discoverable", text: "Google profile, local SEO, service pages, and map presence." },
  { label: "Trusted", text: "Doctor story, patient education, reviews, FAQs, and clear service proof." },
  { label: "Chosen", text: "Offer structure, pricing confidence, booking flow, and follow-up system." }
];

const offers = ["Clinician personal website", "Google Business Profile strategy", "Local patient acquisition system", "Consultation pricing architecture", "Patient education content engine", "Lead capture and follow-up workflow"];

function Logo() {
  return <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-forest text-ivory shadow-glow"><Sparkles size={18} /></div><span className="font-serif text-3xl text-forest">Aleph</span></div>;
}

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-ivory text-ink">
      <header className="sticky top-0 z-50 border-b border-line/80 bg-ivory/90 backdrop-blur-xl">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
          <Logo />
          <div className="hidden items-center gap-8 text-sm font-semibold text-forest/75 md:flex"><a href="#diagnostic" className="hover:text-forest">Diagnostic</a><a href="#method" className="hover:text-forest">Method</a><a href="#solutions" className="hover:text-forest">Solutions</a><a href="#pricing" className="hover:text-forest">Pricing</a></div>
          <a href="#diagnostic" className="focus-ring inline-flex min-h-12 items-center rounded-full bg-terracotta px-5 text-sm font-bold text-white shadow-soft transition hover:brightness-95">Start Growth Audit</a>
        </nav>
      </header>
      <section className="relative"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(197,154,61,0.22),transparent_32%),radial-gradient(circle_at_80%_10%,rgba(15,118,110,0.16),transparent_28%)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.05fr_0.95fr] lg:py-28">
        <div className="flex flex-col justify-center"><span className="mb-6 w-fit rounded-full border border-gold/40 bg-white/60 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-forest">Built for independent clinicians</span><h1 className="font-serif text-5xl leading-[0.98] text-forest md:text-7xl">You built the skill. Aleph helps you build the practice.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-forest/78 md:text-xl">Aleph turns clinical expertise into patient trust, local visibility, confident pricing, and steady footfall without making healthcare feel like hard selling.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row sm:items-center"><a href="#diagnostic" className="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-forest px-7 text-base font-bold text-white shadow-soft transition hover:bg-clinic">Run the Practice Growth Diagnostic <ArrowRight size={18} /></a><span className="text-sm font-semibold text-forest/60">7 signals. 3 minutes. Clear next step.</span></div></div>
        <div className="relative rounded-aleph border border-line bg-white p-5 shadow-soft"><div className="rounded-3xl bg-mist p-5"><div className="flex items-center justify-between rounded-2xl bg-white p-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sage">Practice Readiness</p><p className="mt-1 text-3xl font-black text-forest">74%</p></div><BarChart3 className="text-clinic" size={38} /></div><div className="mt-5 grid gap-3">{diagnosticAreas.map((area, index) => { const score = 68 + index * 5; return <div key={area} className="rounded-2xl bg-white p-4"><div className="flex items-center justify-between text-sm font-bold text-forest"><span>{area}</span><span>{score}%</span></div><div className="mt-3 h-2 rounded-full bg-line"><div className="h-2 rounded-full bg-clinic" style={{ width: score + "%" }} /></div></div>; })}</div><div className="mt-5 rounded-2xl bg-forest p-5 text-white"><p className="text-sm font-bold text-gold">Highest growth leak</p><p className="mt-2 text-xl font-black">Patients cannot clearly understand why you are the right clinician before they book.</p></div></div></div>
      </div></section>
      <section className="border-y border-line bg-white/55 py-14"><div className="mx-auto grid max-w-7xl gap-4 px-5 md:grid-cols-3">{painCards.map((card) => <article key={card.title} className="rounded-2xl border border-line bg-ivory p-7"><h2 className="text-xl font-black text-forest">{card.title}</h2><p className="mt-3 leading-7 text-forest/70">{card.copy}</p></article>)}</div></section>
      <section id="diagnostic" className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-terracotta">Practice Growth Diagnostic</p><h2 className="mt-4 font-serif text-5xl leading-tight text-forest">Find where your practice is leaking growth.</h2><p className="mt-5 text-lg leading-8 text-forest/72">Aleph scores the exact points where independent clinicians lose patients: search visibility, proof of trust, pricing structure, booking clarity, and follow-up discipline.</p></div><div className="rounded-aleph border border-line bg-white p-6 shadow-soft"><div className="grid gap-4 sm:grid-cols-2">{diagnosticAreas.map((area) => <div key={area} className="flex min-h-20 items-center gap-3 rounded-2xl bg-mist p-4"><ShieldCheck className="text-clinic" size={22} /><span className="font-bold text-forest">{area}</span></div>)}<a href="/diagnostic" className="focus-ring flex min-h-20 items-center justify-center gap-2 rounded-2xl bg-gold p-4 font-black text-forest">Start full diagnostic <ArrowRight size={18} /></a></div></div></div></section>
      <section id="method" className="bg-forest py-20 text-white"><div className="mx-auto max-w-7xl px-5"><p className="text-sm font-black uppercase tracking-[0.18em] text-gold">Aleph Method</p><h2 className="mt-4 max-w-3xl font-serif text-5xl leading-tight">Visibility to trust. Trust to footfall. Footfall to a stronger practice.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{method.map((item) => <article key={item.label} className="rounded-2xl border border-white/12 bg-white/8 p-7"><h3 className="text-2xl font-black text-gold">{item.label}</h3><p className="mt-4 leading-7 text-white/76">{item.text}</p></article>)}</div></div></section>
      <section id="solutions" className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-terracotta">Solutions</p><h2 className="mt-4 font-serif text-5xl leading-tight text-forest">A complete growth system, not a basic doctor website.</h2></div><div className="grid gap-3">{offers.map((offer) => <div key={offer} className="flex items-center gap-3 rounded-2xl border border-line bg-white p-5"><Star className="text-gold" size={20} /><span className="font-bold text-forest">{offer}</span></div>)}</div></div></section>
      <section id="pricing" className="border-y border-line bg-mist py-20"><div className="mx-auto max-w-7xl px-5"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.18em] text-terracotta">Pricing Strategy</p><h2 className="mt-4 font-serif text-5xl leading-tight text-forest">Packages will be outcome-based, not cheap template pricing.</h2><p className="mt-5 text-lg leading-8 text-forest/72">Sprint 4 will lock Aleph Starter, Growth, Authority, and Concierge with INR pricing, deliverables, and clinician-fit logic.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{["Starter", "Growth", "Authority"].map((tier) => <article key={tier} className="rounded-2xl border border-line bg-white p-7"><h3 className="text-2xl font-black text-forest">Aleph {tier}</h3><p className="mt-4 leading-7 text-forest/70">Reserved for Sprint 4 pricing lock after diagnostic and lead workflow are stable.</p></article>)}</div></div></section>
      <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 text-sm text-forest/65 md:flex-row md:items-center md:justify-between"><Logo /><div className="flex flex-wrap gap-5"><span className="inline-flex items-center gap-2"><MapPin size={16} /> Built from Hyderabad for global clinicians</span><span className="inline-flex items-center gap-2"><CalendarCheck size={16} /> Strategy call ready</span></div></footer>
    </main>
  );
}
